# Generated by Django 2.2 on 2020-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('OK', 'ok'), ('ERROR', 'error'), ('EXCEPTION', 'exception')], default='OK', max_length=9, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='end_at',
            field=models.DateTimeField(verbose_name='execution end timestamp'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='start_at',
            field=models.DateTimeField(verbose_name='execution start timestamp'),
        ),
    ]
