# Generated by Django 2.2 on 2020-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_auto_20201013_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('OK', 'ok'), ('ERROR', 'error'), ('EXCEPTION', 'exception')], max_length=9, verbose_name='status'),
        ),
    ]
