# Generated by Django 3.1.2 on 2020-10-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('enable', models.BooleanField(default=True, verbose_name='enable')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.action', verbose_name='action')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reaction.reaction', verbose_name='reaction')),
            ],
        ),
    ]
