# Generated by Django 3.1.2 on 2020-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('script', models.FileField(upload_to='scripts')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
            ],
        ),
    ]
